version: '3.3'

services:
  # ========================
  # VPN
  # ========================

  vpn:
    extends:
      file: ./docker/vpn.yml
      service: vpn

  # ========================
  # Management
  # ========================

  radarr:
    extends:
      file: ./docker/management.yml
      service: radarr

  sonarr:
    extends:
      file: ./docker/management.yml
      service: sonarr

  prowlarr:
    extends:
      file: ./docker/management.yml
      service: prowlarr

  overseerr:
    extends:
      file: ./docker/management.yml
      service: overseerr

  # ========================
  # Media
  # ========================

  plex:
    extends:
      file: ./docker/media.yml
      service: plex

  tautulli:
    extends:
      file: ./docker/media.yml
      service: tautulli

  plex-meta-manager:
    extends:
      file: ./docker/media.yml
      service: plex-meta-manager

  # ========================
  # Tools
  # ========================

  homepage:
    extends:
      file: ./docker/tools.yml
      service: homepage

  firefox:
    extends:
      file: ./docker/tools.yml
      service: firefox
  
  traefik:
    extends:
      file: ./docker/tools.yml
      service: traefik

  transmission:
    extends:
      file: ./docker/tools.yml
      service: transmission
