version: '3.3'

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/radarr:/config
      - ${LIBRARY_MOVIES_PATH:-~/Media Library/Movies}:/movies #optional
      - ${DOWNLOAD_PATH:-~/Media Library/Download}:/downloads #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${RADARR_SUBDOMAIN:-radarr.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - 'traefik.http.routers.radarr.middlewares=authelia@docker'
      - 'traefik.http.routers.radarr.tls=true'
      - homepage.group=Management
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://${RADARR_SUBDOMAIN:-radarr.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Movies management
      - homepage.weight=5
      - homepage.widget.type=radarr
      - homepage.widget.url=http://vpn:7878
      - homepage.widget.key=${RADARR_TOKEN}
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/sonarr:/config
      - ${LIBRARY_TV_PATH:-~/Media Library/TV}:/tv #optional
      - ${DOWNLOAD_PATH:-~/Media Library/Download}:/downloads #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARR_SUBDOMAIN:-sonarr.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - 'traefik.http.routers.sonarr.middlewares=authelia@docker'
      - 'traefik.http.routers.sonarr.tls=true'
      - homepage.group=Management
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://${SONARR_SUBDOMAIN:-sonarr.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=TV shows management
      - homepage.weight=5
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://vpn:8989
      - homepage.widget.key=${SONARR_TOKEN}
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    depends_on:
      - vpn
    network_mode: service:vpn
    profiles:
      - book
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/readarr:/config
      - ${LIBRARY_BOOKS_PATH:-~/Media Library/Books}:/books #optional
      - ${DOWNLOAD_PATH:-~/Media Library/Download}:/downloads #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`${READARR_SUBDOMAIN:-readarr.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      - 'traefik.http.routers.readarr.middlewares=authelia@docker'
      - 'traefik.http.routers.readarr.tls=true'
      - homepage.group=Management
      - homepage.name=Readarr
      - homepage.icon=readarr.png
      - homepage.href=http://${READARR_SUBDOMAIN:-readarr.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Books management
      - homepage.weight=5
      - homepage.widget.type=readarr
      - homepage.widget.url=http://vpn:8787
      - homepage.widget.key=${READARR_TOKEN}
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_SUBDOMAIN:-prowlarr.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - 'traefik.http.routers.prowlarr.middlewares=authelia@docker'
      - 'traefik.http.routers.prowlarr.tls=true'
      - homepage.group=Management
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://${PROWLARR_SUBDOMAIN:-prowlarr.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Indexer management
      - homepage.weight=10
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://vpn:9696
      - homepage.widget.key=${PROWLARR_TOKEN}
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/overseerr:/config
    ports:
      - ${OVERSEERR_PORT:-5055}:5055
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`${OVERSEERR_SUBDOMAIN:-overseerr.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - 'traefik.http.routers.overseerr.middlewares=authelia@docker'
      - 'traefik.http.routers.overseerr.tls=true'
      - homepage.group=Management
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=http://${OVERSEERR_SUBDOMAIN:-overseerr.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Media requests
      - homepage.weight=1
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr:5055
      - homepage.widget.key=${OVERSEERR_TOKEN}
    restart: unless-stopped
