version: '3.3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: service:vpn
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - VERSION=docker
    volumes:
      - ../config/plex:/config
      - ${LIBRARY_TV_PATH:-~/Movies/Plex/TV}:/tv
      - ${LIBRARY_MOVIES_PATH:-~/Movies/Plex/Movies}:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${PLEX_SUBDOMAIN:-plex.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://${PLEX_SUBDOMAIN:-plex.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Media server
      - homepage.weight=1
      - homepage.widget.type=plex
      - homepage.widget.url=http://vpn:32400
      - homepage.widget.key=${PLEX_TOKEN}
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    profiles:
      - book
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ../config/calibre-web:/config
      - ${LIBRARY_BOOKS_PATH:-~/Movies/Books}:/books
    ports:
      - ${CALIBRE_WEB_PORT:-8083}:8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.rule=Host(`${CALIBRE_WEB_SUBDOMAIN:-calibre-web.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
      - homepage.group=Media
      - homepage.name=Calibre Web
      - homepage.icon=calibre-web.png
      - homepage.href=http://${CALIBRE_WEB_SUBDOMAIN:-calibre-web.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Books library
      - homepage.weight=5
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    profiles:
      - plex_plugin
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/tautulli:/config
    ports:
      - ${TAUTULLI_PORT:-8181}:8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`${TAUTULLI_SUBDOMAIN:-tautulli.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=http://${TAUTULLI_SUBDOMAIN:-plex.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Plex monitoring
      - homepage.weight=5
      - homepage.widget.type=tautulli
      - homepage.widget.url=http://tautulli:8181
      - homepage.widget.key=${TAUTULLI_TOKEN}
    restart: unless-stopped

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    profiles:
      - plex_plugin
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/pmm:/config
    restart: unless-stopped