version: '3.3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - VERSION=docker
    ports:
      - ${PLEX_PORT:-32400}:32400
    volumes:
      - ../config/plex:/config
      - ${LIBRARY_TV_PATH:-~/Movies/Plex/TV}:/tv
      - ${LIBRARY_MOVIES_PATH:-~/Movies/Plex/Movies}:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${PLEX_SUBDOMAIN:-plex.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://${PLEX_SUBDOMAIN:-plex.media}.${DOMAIN:-localhost}
      - homepage.description=Media server
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/tautulli:/config
    ports:
      - ${TAUTULLI_PORT:-8181}:8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`${TAUTULLI_SUBDOMAIN:-tautulli.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=http://${TAUTULLI_SUBDOMAIN:-plex.media}.${DOMAIN:-localhost}
      - homepage.description=Plex monitoring
    restart: unless-stopped

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/pmm:/config
    restart: unless-stopped