version: '3.3'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    depends_on: 
      - authelia
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - "--api.insecure=true"
      - "--ping=true"
      - '--log=true'
      - '--log.level=INFO'
      - '--log.filepath=/config/traefik.log'
      - --providers.file.directory=/config/
      - --providers.file.watch=true
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - '--global.sendAnonymousUsage=false'
      - '--entryPoints.http=true'
      - '--entryPoints.http.address=:80/tcp'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
      - '--entryPoints.https=true'
      - '--entryPoints.https.address=:443/tcp'
    ports:
      - ${TRAEFIK_PORT:-80}:80
      - ${TRAEFIK_SECURE_PORT:-443}:443
      - ${TRAEFIK_DASHBOARD_PORT:-8080}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_DASHBOARD_SUBDOMAIN:-traefik.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
      - 'traefik.http.routers.traefik-dashboard.middlewares=authelia@docker'
      - 'traefik.http.routers.traefik-dashboard.tls=true'
      - homepage.group=Tools
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=http://${TRAEFIK_DASHBOARD_SUBDOMAIN:-traefik.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Reverse proxy
      - homepage.weight=5
      - homepage.widget.type=traefik
      - homepage.widget.url=http://traefik:8080
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 5s
      retries: 10

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    expose:
      - 9091
    volumes:
      - ${PWD}/config/authelia/config:/config
    environment:
      TZ: "UTC"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`${AUTH_SUBDOMAIN:-auth.media}.${DOMAIN:-localhost}`)'
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - 'traefik.http.routers.authelia.entryPoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://${AUTH_SUBDOMAIN:-auth.media}.${DOMAIN:-localhost}'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - homepage.group=Tools
      - homepage.name=Logout
      - homepage.href=http://${AUTH_SUBDOMAIN:-auth.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Authentication management
      - homepage.weight=1

  redis:
    container_name: redis
    image: redis:4.0-alpine
    ports:
      - "6379:6379"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_VAR_TITLE: Medias
    ports:
      - ${HOMEPAGE_PORT:-6900}:3000
    volumes:
      - ../config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock
    command: [sh, -c, "cp -n -u /app/config/templates/*.yaml /app/config && node server.js"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${HOME_SUBDOMAIN:-media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - 'traefik.http.routers.homepage.middlewares=authelia@docker'
      - 'traefik.http.routers.homepage.tls=true'
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - DOCKER_MODS=linuxserver/mods:transmission-transmissionic
    volumes:
      - ../config/transmission:/config
      - ${DOWNLOAD_PATH:-~/Media Library/Download}:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`${TRANSMISSION_SUBDOMAIN:-download.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - 'traefik.http.routers.transmission.middlewares=authelia@docker'
      - 'traefik.http.routers.transmission.tls=true'
      - homepage.group=Tools
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://${TRANSMISSION_SUBDOMAIN:-download.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Download client
      - homepage.weight=1
      - homepage.widget.type=transmission
      - homepage.widget.url=http://vpn:9091
    restart: unless-stopped

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    profiles:
      - advanced_tools
    depends_on:
      - vpn
    security_opt:
      - seccomp:unconfined
    network_mode: service:vpn
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - CUSTOM_PORT=5800
    volumes:
      - ../config/firefox:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefox.rule=Host(`${FIREFOX_SUBDOMAIN:-browser.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.firefox.loadbalancer.server.port=5800"
      - 'traefik.http.routers.firefox.middlewares=authelia@docker'
      - 'traefik.http.routers.firefox.tls=true'
      - homepage.group=Tools
      - homepage.name=Firefox
      - homepage.icon=firefox.png
      - homepage.href=http://${FIREFOX_SUBDOMAIN:-browser.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Web browser
      - homepage.weight=1
    shm_size: "1gb"
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    network_mode: service:vpn
    profiles:
      - book
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ../config/calibre:/config
      - ${LIBRARY_BOOKS_PATH:-~/Media Library/Books}:/books
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`${CALIBRE_SUBDOMAIN:-calibre.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.calibre.loadbalancer.server.port=8080"
      - 'traefik.http.routers.calibre.middlewares=authelia@docker'
      - 'traefik.http.routers.calibre.tls=true'
      - homepage.group=Tools
      - homepage.name=Calibre
      - homepage.icon=calibre.png
      - homepage.href=http://${CALIBRE_SUBDOMAIN:-calibre.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=Ebook manager
      - homepage.weight=1
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    profile:
      - advanced_tools
    entrypoint: [
      "/bin/sh",
      "-c",
      "
        cp /config/templates/filebrowser.db /database/filebrowser.db
        && cp /config/templates/settings.json /config/settings.json
        && /init
      "
    ]
    environment:
      - PUID=${USER_ID:-1000}
      - PGID=${GROUP_ID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ../config/filebrowser:/config
      - ../config/filebrowser:/database
      - ${LIBRARY_MOVIES_PATH:-~/Media Library/Movies}:/srv/Movies:ro
      - ${LIBRARY_TVSHOWS_PATH:-~/Media Library/TV Shows}:/srv/TV Shows:ro
      - ${LIBRARY_BOOKS_PATH:-~/Media Library/Books}:/srv/Books:ro
      - ${LIBRARY_DOWNLOADS_PATH:-~/Media Library/Download}:/srv/Download:ro
    ports:
      - ${FILEBROWSER_PORT:-6930}:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_SUBDOMAIN:-filebrowser.media}.${DOMAIN:-localhost}`)"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - 'traefik.http.routers.filebrowser.middlewares=authelia@docker'
      - 'traefik.http.routers.filebrowser.tls=true'
      - homepage.group=Tools
      - homepage.name=Filebrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://${FILEBROWSER_SUBDOMAIN:-filebrowser.media}.${DOMAIN:-localhost}:${TRAEFIK_PORT:-80}
      - homepage.description=File manager
      - homepage.weight=1

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=0
    restart: unless-stopped