version: "3.3"

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      # - 8000:8000/tcp # Control server
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - ${RADARR_PORT:-7878}:7878 # Radarr
      - ${SONARR_PORT:-8989}:8989 # Sonarr
      - ${READARR_PORT:-8787}:8787 # Readarr
      - ${PROWLARR_PORT:-9696}:9696 # Prowlarr
      - ${TRANSMISSION_PORT:-9091}:9091 # Transmission
      - ${FIREFOX_PORT:-5800}:5800 # Firefox
      - ${CALIBRE_DESKTOP_PORT:-6920}:8080
      - ${CALIBRE_DESKTOP_SECURE_PORT:-6201}:8181
      - ${CALIBRE_WEBSERVER_PORT:-6202}:8081
    volumes:
      - ../config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
    labels:
      - homepage.group=Tools
      - homepage.name=VPN
      - homepage.icon=gluetun.png
      - homepage.weight=10
      - homepage.widget.type=gluetun
      - homepage.widget.url=http://vpn:8000
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
